# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Profullstack.PairUX
PackageVersion: 0.13.5
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/profullstack/pairux.com/releases/download/v0.13.5/PairUX.Setup.0.13.5.exe
    InstallerSha256: A715648B8E55BA2D7CBB54780A2CB343E80EC6D0EB5CB29B1FC732C2E4595D2C
ManifestType: installer
ManifestVersion: 1.10.0
